### ISSUE TITLE
Broken Dependency

### ISSUE THREAD

**Issue by RyanHoldren** [jitsi/jicoco#126]
`jitsi-config` has a dependecy on `jitsi-metaconfig`:
```
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>jitsi-metaconfig</artifactId>
            <version>c3d8c51747</version>
        </dependency>
```
But that project doesn't seem to be published [in your maven repository](https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/org/jitsi)?

**Comment by bbaldino** [comment]
That project is currently published via jitpack.

**Comment by RyanHoldren** [comment]
I'm not able to resolve it, no.

```
Could not find org.jitsi:jitsi-metaconfig:c3d8c51747.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jitsi/jitsi-metaconfig/c3d8c51747/jitsi-metaconfig-c3d8c51747.pom
       - https://github.com/jitsi/jitsi-maven-repository/raw/master/releases/org/jitsi/jitsi-metaconfig/c3d8c51747/jitsi-metaconfig-
```

Take a look at [the contents of the repository](https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/org/jitsi) and you can see that `jitsi-metaconfig` is not there.

**Comment by bbaldino** [comment]
Yes, it is known that it is not in the jitsi repository.  That package is hosted in jitpack, which automatically creates artifacts for github maven projects.

**Comment by bbaldino** [comment]
Do you see any errors in maven logs about jitpack?  Might need to turn some verbosity on.

**Comment by RyanHoldren** [comment]
I figured it out!

I was pointed directly at GitHub like this:
```
repositories {
	maven {
		url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases/"
		content {
			includeGroupByRegex "org\\.jitsi.*"
		}
	}
}
```

... when I point at JitPack instead, it starts working:

```
repositories {
	maven {
		url "https://jitpack.io"
		content {
			includeGroupByRegex "org\\.jitsi.*"
		}
	}
}
```

Thanks for pointing me in the right direction, @bbaldino

**Comment by bbaldino** [comment]
Hm, but that repo should have been taken care of by Jicoco itself?  Or are you trying to use jitsi-metaconfig directly (not via Jicoco)?

**Comment by RyanHoldren** [comment]
I'm trying to use Ice4J actually, which depends on `jitsi-config`, which depends on `jitsi-metaconfig`.

**Comment by bbaldino** [comment]
Hm, `jitsi-config` lists `jitpack` as a repository, so not sure why that wouldn't have resolved, maybe the repositories aren't transitive in this case.
