### ISSUE TITLE
EventAdmin will miss preregistered EventHandlers

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jicoco#13]
Currently we do not fetch the list of all currently registered EventHandlers, so we will miss all those which have registered before ServiceListener has been registered.

**Comment by paweldomas** [comment]
https://github.com/jitsi/jicoco/blob/master/src/main/java/org/jitsi/eventadmin/EventAdminImpl.java#L116

**Comment by Neustradamus** [comment]
@paweldomas: The problem is always here?
